export var ConsoleConfigKeyMapping = {
  features: 'CHANNEL_FEATURE_STATUS',
  gray: 'FEATURE_STATUS',
  accountLoginLink: 'ACCOUNT_LOGIN_LINK',
  isCertified: 'IS_CERTIFIED',
  channel: 'CHANNEL',
  fEnv: 'fEnv',
  secToken: 'SEC_TOKEN',
  locale: 'LOCALE',
  lang: 'LANG',
  accountName: 'ACCOUNT_NAME',
  mainAccountPK: 'MAIN_ACCOUNT_PK',
  currentPK: 'CURRENT_PK',
  accountType: 'ACCOUNT_TYPE',
  channelStatus: 'CHANNEL_FEATURE_STATUS',
  links: 'CHANNEL_LINKS',
  openStatus: 'OPEN_STATUS',
  grayStatus: 'FEATURE_STATUS',
  labels: 'LABELS',
  regions: 'REGIONS',
  ruleConfig: 'RULE_CONFIG',
  staticApi: 'STATIC_API',
  regionBarSetting: 'REGION_BAR_SETTING',
  userPreference: 'USER_PREFERENCE',
  newVersion: 'NEW_VERSION'
};